### ISSUE TITLE
Persona Analysis 

### ISSUE THREAD

**Issue by ilan-pinto** [RHEcosystemAppEng/SaaSi#3]
## Goal
Identify who might be the users of the SaaSi application per use cases. 

## Deliverables 
- Persona Analysis doc

**Comment by dmartinol** [comment]
Persona analysis in slide 24 of [SaaSi presentation](https://docs.google.com/presentation/d/1sIX-0VJCP_wmkgZdysizkHBnDcm9Nu0BhcnVRZzynVA/edit?hl=en&forcehl=1#slide=id.g1c26e6354eb_0_0)
