### ISSUE TITLE
create infra deployment

### ISSUE THREAD

**Issue by dmartinol** [RHEcosystemAppEng/SaaSi#44]
TODO: when to git clone the other repository
Run ansible playbopok
Store kubeconfig in the agreed folder structure

**Comment by zvigrinberg** [comment]
Created the code that invokes the playbook, and fetch the kubeconfig' details from playbook's output , fixed some bugs and now testing the integration of the new cluster with the app deployment.

**Comment by zvigrinberg** [comment]
Finished silent demo recording of exporting-->provisioning-->deploying.

**Comment by zvigrinberg** [comment]
Task Completed after thorough tests and complete demo of the whole steps in the procedure
