### ISSUE TITLE
Propose changes to `Konveyor Crane` to expose parameters in order to simplify integration with external applications 

### ISSUE THREAD

**Issue by IlonaShishov** [RHEcosystemAppEng/SaaSi#5]
TODO:
1) open issue in the `Konveyor Crane` GitHub Repository (https://github.com/migtools/crane/issues)
2) open PR with requested changes as a solution to the issue

Target changes:
1) move Global Flags from restricted internal directory
2) publicize command options struct fields in all packages

**Comment by dmartinol** [comment]
Moved to #50
